"""
Admin settings for CDB app.

Generated by 'django-admin startproject' using Django 1.11.6.

For more information on this file, see
https://docs.djangoproject.com/en/1.11/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.11/ref/settings/
"""

from django.contrib import admin
from .models import Iasio, Ias, Property


# Register your models here.
admin.site.register(Ias)
admin.site.register(Property)
admin.site.register(Iasio)
