# Generated by Django 2.0.2 on 2018-03-22 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cdb', '0002_auto_20180322_1739'),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('value', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'PROPERTY',
            },
        ),
        migrations.AddField(
            model_name='ias',
            name='properties',
            field=models.ManyToManyField(db_table='IAS_PROPERTY', to='cdb.Property'),
        ),
    ]
