# Generated by Django 2.0.4 on 2018-06-13 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cdb', '0004_auto_20180411_1457'),
    ]

    operations = [
        migrations.AddField(
            model_name='iasio',
            name='doc_url',
            field=models.CharField(blank=True, db_column='docUrl', max_length=256),
        ),
    ]
