# Generated by Django 2.0.4 on 2018-10-09 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cdb', '0005_iasio_doc_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ias',
            name='properties',
        ),
        migrations.DeleteModel(
            name='Iasio',
        ),
        migrations.DeleteModel(
            name='Ias',
        ),
        migrations.DeleteModel(
            name='Property',
        ),
    ]
