# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-06 21:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alarms', '0003_auto_20171110_2155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alarm',
            name='mode',
            field=models.CharField(choices=[('2', 'CLOSING'), ('6', 'DEGRADED'), ('1', 'INITIALIZATION'), ('4', 'MAINTENANCE'), ('5', 'OPERATIONAL'), ('3', 'SHUTTEDOWN'), ('0', 'STARTUP'), ('7', 'UNKNOWN')], default=0, max_length=1),
        ),
    ]
