# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-26 19:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alarms', '0005_auto_20171213_1600'),
    ]

    operations = [
        migrations.AddField(
            model_name='alarm',
            name='validity',
            field=models.CharField(choices=[('1', 'RELIABLE'), ('0', 'UNRELIABLE')], default=0, max_length=1),
        ),
    ]
