# Generated by Django 2.0.2 on 2018-03-22 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alarms', '0007_auto_20180216_2010'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Alarm',
        ),
    ]
