FROM centos:7

# Install python
RUN yum install -y gcc openssl-devel bzip2-devel libffi-devel wget make
RUN yum install -y mysql-devel sqlite-devel
WORKDIR /usr/src
RUN wget https://www.python.org/ftp/python/3.7.3/Python-3.7.3.tgz
RUN tar xzf Python-3.7.3.tgz
WORKDIR /usr/src/Python-3.7.3
RUN ./configure --enable-optimizations
RUN make install
RUN rm -rf /usr/src/Python-3.7.3
RUN rm -rf /usr/src/Python-3.7.3.tgz
RUN update-alternatives --install /usr/bin/python python /usr/local/bin/python3.7 1 &&\
  update-alternatives --install /usr/bin/pip pip /usr/local/bin/pip3.7 1

# Install requirements
WORKDIR /usr/src/ias-webserver
COPY requirements.txt .
RUN pip install -r requirements.txt

# Expose port
EXPOSE 8000
