FROM python:3.6.5-alpine3.7

# Install requirements
RUN apk add --update
RUN apk add gcc musl-dev linux-headers
WORKDIR /usr/src/ias-webserver
COPY requirements.txt .
RUN pip install -r requirements.txt

# Expose port
EXPOSE 8001
