# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-25 21:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alarm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(default=0)),
                ('core_timestamp', models.PositiveIntegerField()),
                ('core_id', models.CharField(max_length=100)),
                ('running_id', models.CharField(max_length=100)),
            ],
        ),
    ]
