# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-25 21:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alarm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alarm',
            name='mode',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
