# Generated by Django 2.0.2 on 2018-04-10 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolve_at', models.DateTimeField(null=True)),
                ('alarm_id', models.CharField(max_length=64)),
                ('message', models.CharField(max_length=256, null=True)),
                ('status', models.IntegerField(choices=[('0', 'CLOSE'), ('1', 'OPEN')], default=1)),
            ],
        ),
    ]
