# Generated by Django 2.0.2 on 2018-04-11 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='alarm_id',
            field=models.CharField(db_index=True, max_length=64),
        ),
    ]
