# Generated by Django 2.0.4 on 2018-04-12 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_auto_20180411_1457'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='resolved_at',
            new_name='acknoledged_at',
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.IntegerField(choices=[('1', 'ACK'), ('0', 'UNACK')], default=0),
        ),
    ]
