# Generated by Django 2.0.4 on 2018-04-30 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_auto_20180412_1609'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='acknoledged_at',
            new_name='acknowledged_at',
        ),
    ]
