# Generated by Django 2.0.4 on 2018-06-14 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0005_auto_20180430_1931'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='cleared_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.IntegerField(choices=[('1', 'ACK'), ('3', 'CLEARED_ACK'), ('2', 'CLEARED_UNACK'), ('0', 'UNACK')], default=0),
        ),
    ]
