# Generated by Django 2.0.4 on 2018-06-14 21:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0005_auto_20180430_1931'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShelveRegistry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shelved_at', models.DateTimeField(auto_now_add=True)),
                ('unshelved_at', models.DateTimeField(null=True)),
                ('alarm_id', models.CharField(db_index=True, max_length=64)),
                ('message', models.CharField(max_length=256)),
                ('timeout', models.DurationField(default=datetime.timedelta(0, 7200))),
                ('status', models.IntegerField(choices=[('1', 'SHELVED'), ('0', 'UNSHELVED')], default=1)),
            ],
        ),
    ]
