# Generated by Django 2.0.4 on 2018-06-19 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0006_shelveregistry'),
        ('tickets', '0006_auto_20180614_2303'),
    ]

    operations = [
    ]
