# Generated by Django 2.0.4 on 2018-07-30 20:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0007_merge_20180619_2051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shelveregistry',
            name='timeout',
            field=models.DurationField(default=datetime.timedelta(0, 43200)),
        ),
    ]
