# Generated by Django 2.0.8 on 2018-11-05 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0008_auto_20180730_2035'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticket',
            options={'default_permissions': ('add', 'change', 'delete', 'view')},
        ),
    ]
