# Generated by Django 2.0.8 on 2018-11-06 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0009_auto_20181105_2039'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticket',
            options={'default_permissions': ('add', 'change', 'delete', 'view', 'acknowledge')},
        ),
    ]
