# Generated by Django 2.0.4 on 2018-11-08 19:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0009_ticket_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='shelveregistry',
            name='user',
            field=models.CharField(default=django.utils.timezone.now, max_length=150),
            preserve_default=False,
        ),
    ]
