# Generated by Django 2.0.8 on 2018-11-06 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0010_auto_20181106_1610'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shelveregistry',
            options={'default_permissions': ('add', 'change', 'delete', 'view', 'shelve')},
        ),
    ]
