# Generated by Django 2.0.8 on 2018-11-08 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0011_auto_20181106_2208'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shelveregistry',
            options={'default_permissions': ('add', 'change', 'delete', 'view', 'shelve', 'unshelve')},
        ),
    ]
