# Generated by Django 2.0.8 on 2018-11-08 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0012_auto_20181108_1534'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shelveregistry',
            options={'default_permissions': ('add', 'change', 'delete', 'view', 'unshelve')},
        ),
    ]
