# Generated by Django 2.0.8 on 2018-11-08 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0013_auto_20181108_1803'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shelveregistry',
            options={'default_permissions': ('change', 'delete', 'view', 'add', 'unshelve')},
        ),
        migrations.AlterModelOptions(
            name='ticket',
            options={'default_permissions': ('change', 'delete', 'view', 'acknowledge')},
        ),
    ]
