# Generated by Django 2.0.8 on 2018-11-14 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0010_shelveregistry_user'),
        ('tickets', '0014_auto_20181108_2002'),
    ]

    operations = [
    ]
