# Generated by Django 2.0.4 on 2018-08-31 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panels', '0002_auto_20180830_1919'),
    ]

    operations = [
        migrations.AddField(
            model_name='alarmconfig',
            name='custom_name',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='alarmconfig',
            name='tags',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
