# Generated by Django 2.0.4 on 2018-10-19 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panels', '0005_auto_20181010_1900'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='placemark',
            name='coordinates_type',
        ),
        migrations.RemoveField(
            model_name='placemark',
            name='x',
        ),
        migrations.RemoveField(
            model_name='placemark',
            name='y',
        ),
    ]
