# Generated by Django 2.0.8 on 2018-11-12 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panels', '0006_auto_20181019_1855'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alarmconfig',
            options={'default_permissions': ('add', 'change', 'delete', 'view')},
        ),
    ]
