# Generated by Django 2.0.8 on 2018-11-12 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panels', '0008_auto_20181112_1642'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='file',
            options={'default_permissions': ('add', 'change', 'delete', 'view')},
        ),
    ]
