# Generated by Django 2.0.8 on 2019-01-16 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panels', '0010_auto_20181128_1436'),
    ]

    operations = [
        migrations.DeleteModel(
            name='File',
        ),
    ]
