# Generated by Django 2.0.8 on 2019-01-24 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panels', '0011_delete_file'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='alarmconfig',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='alarmconfig',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='alarmconfig',
            name='placemark',
        ),
        migrations.RemoveField(
            model_name='alarmconfig',
            name='type',
        ),
        migrations.RemoveField(
            model_name='alarmconfig',
            name='view',
        ),
        migrations.DeleteModel(
            name='AlarmConfig',
        ),
        migrations.DeleteModel(
            name='Type',
        ),
        migrations.DeleteModel(
            name='View',
        ),
    ]
